spring:
  jpa:
    show-sql: true
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.224.129.134:3306/sys?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: qingtian
eureka:
  client:
    service-url:
      defaultZOone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true
